# -*- coding: utf-8 -*-
"""practical 6.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyJcF1hN3Tlm7JGhLSlU3bsZXSHlxeUK
"""

my_dict={'name':'jyoti','class':12,'age':23}
#accessing the value
print(my_dict['coarse'])         #error

print(my_dict.get('coarse','not there'))

#modifying or adding elements
my_dict['coarse']='data science'        #adding element
print(my_dict)

my_dict['coarse']='data science11'         #modifying element
print(my_dict)

#deleting any key value pair
#del keyword
#pop method
del my_dict['class']

print(my_dict)

a=my_dict.pop ('age')

print(my_dict)

#built in methods
#keys()..........print all keys in the dictionary(list)
#values()..........print all values
#items().....print all key value pair
#update()..........can add multiple key value pairs or we can say another dictionary in the existing dictionary
#clear()..........will delete all the key value pairs in the dictionary

my_dict1={'office':'regex','HR':['Prachi mam,Karishma mam'],'city':'jaipur'}
my_dict1.keys()

my_dict1.values()

my_dict1.items()

my_dict1.update({'city':'updaipur'})
print(my_dict1)

my_dict1.clear()
print(my_dict1)

#BOOLtype/Booleantype(True/False)
is_passed=True
is_passed=False
in_class=False
#Nonetype
classes=None